### ISSUE TITLE
Failed to execute sshdo --learn with python3

### ISSUE THREAD

**Issue by jbuggie** [raforg/sshdo#2]
When using python3, sshdo --learn gives the following errors:

Traceback (most recent call last):
  File "./sshdo", line 886, in <module>
    main()
  File "./sshdo", line 110, in main
    sys.exit(learn(config_fname, args, do_accepting))
  File "./sshdo", line 194, in learn
    for fname, l, line, msgtype, user, label, cmd, cfg in sshdo_log_messages(config, filenames):
  File "./sshdo", line 175, in sshdo_log_messages
    if not ' %s[' % prog_name in line and not ' %s:' % prog_name in line:
TypeError: a bytes-like object is required, not 'str'

**Comment by raforg** [comment]
Hi, Thanks for reporting that. The problem was with reading gzipped auth.log files.
gzip.open()'s mode argument has changed meaning, and my automatic testing only
uses self-contained log data, so it wasn't catching that.
Please try the latest commit and see how that goes.

**Comment by jbuggie** [comment]
Thank you for fixing it so quickly. Latest version works with python3 now. Very nice expansion of ssh restricted command, btw.
